
SELECT [CPF]
      ,[NOME]
  FROM [TABELA DE CLIENTES];

SELECT [CPF] AS INDENTIFICADOR
      ,[NOME] AS [NOME DO CLIENTE]
FROM [TABELA DE CLIENTES]


SELECT * FROM [TABELA DE PRODUTOS]

--DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1000889';

SELECT [CODIGO DO PRODUTO], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS]  WHERE [CODIGO DO PRODUTO] = '1000889';

SELECT [CODIGO DO PRODUTO], [NOME DO PRODUTO], [PRECO DE LISTA] FROM [TABELA DE PRODUTOS]  WHERE [SABOR] = 'Limão';

UPDATE [TABELA DE PRODUTOS] SET [PRECO DE LISTA] = 1.1 * [PRECO DE LISTA] WHERE SABOR = 'Limão';

UPDATE [TABELA DE VENDEDORES] 
SET [PERCENTUAL COMISSÃO] = 1.1 * [PERCENTUAL COMISSÃO]
WHERE [MATRICULA] = '00239';

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM = 'PET';
SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] = 17.6088;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] < 10;
SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] > 10;
SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] > 13.2121;
SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] >= 13.2121;

 SELECT * FROM [TABELA DE VENDEDORES] 
 WHERE [PERCENTUAL COMISSÃO] > 0.10;

 SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] >= '1995-09-11';

 SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] <= '1995-09-11';

 SELECT * FROM [TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO]) = 9;

 SELECT * FROM [TABELA DE VENDEDORES] 
 WHERE MATRICULA = 00233 OR [PERCENTUAL COMISSÃO] > 0.09;