
SELECT [CPF]
      ,[NOME]
  FROM [TABELA DE CLIENTES];

SELECT [CPF] AS INDENTIFICADOR
      ,[NOME] AS [NOME DO CLIENTE]
FROM [TABELA DE CLIENTES]


SELECT * FROM [TABELA DE PRODUTOS]

--DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1000889';

SELECT [CODIGO DO PRODUTO], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS]  WHERE [CODIGO DO PRODUTO] = '1000889';

SELECT [CODIGO DO PRODUTO], [NOME DO PRODUTO], [PRECO DE LISTA] FROM [TABELA DE PRODUTOS]  WHERE [SABOR] = 'Limão';

UPDATE [TABELA DE PRODUTOS] SET [PRECO DE LISTA] = 1.1 * [PRECO DE LISTA] WHERE SABOR = 'Limão';

UPDATE [TABELA DE VENDEDORES] 
SET [PERCENTUAL COMISSÃO] = 1.1 * [PERCENTUAL COMISSÃO]
WHERE [MATRICULA] = '00239';