
SELECT [CPF]
      ,[NOME]
  FROM [TABELA DE CLIENTES];

SELECT [CPF] AS INDENTIFICADOR
      ,[NOME] AS [NOME DO CLIENTE]
FROM [TABELA DE CLIENTES]


SELECT * FROM [TABELA DE PRODUTOS]

--DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1000889';

SELECT [CODIGO DO PRODUTO], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS]  WHERE [CODIGO DO PRODUTO] = '1000889';

SELECT [CODIGO DO PRODUTO], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS]  WHERE [SABOR] = 'Limão';
