--CPF DO CLIENTE
--O NOME COMPLETO DO CLIENTE
--ENDEREÇO COM RUA, BAIRRO, CIDADEM ESTADO E CEP
--DATA DE NASCIMENTO
--A IDADE 
--GENERO
--O LIMITE DO CREDITO DO CLIENTE PARA ELE COMPRAR PRODUTOS NA EMPRESA
--O VOLUME MINIMO DE PRODUTOS QUE ELE PODE COMPRAR
--SE ELE JÁ REALIZOU A PRIMEIRA COMPRA

CREATE TABLE [TABELA DE CLIENTES]
([CPF] [CHAR] (11),
[NOME] [VARCHAR] (100),
[ENDERECO1] [VARCHAR] (150),
[ENDERECO2] [VARCHAR] (150),
[BAIRRO] [VARCHAR] (50),
[CIDADE] [VARCHAR] (50),
[ESTADO] [CHAR] (2),
[CEP] [CHAR] (8),
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [CHAR](1),
[LIMITE DE CREDITO] [MONEY],
[VOLUME DE COMPRA] [FLOAT],
[PRIMEIRA COMPRA] [BIT]);

CREATE TABLE [TABELA DE VENDEDORES]
([MATRICULA] VARCHAR (5),
[NOME] VARCHAR (100),
[PERCENTUAL COMISSÃO] FLOAT);