USE [SUCOS_VENDAS] -- Conecta o banco de dados

 -- item 1
DROP TABLE [TABELA DE VENDEDORES]; 

 -- item 2
CREATE TABLE [TABELA DE VENDEDORES](
    [MATRICULA] [varchar](20) NOT NULL,
    [NOME] [varchar](100) NULL,
    [PERCENTUAL COMISSÃO] [varchar](20) NOT NULL,
 CONSTRAINT [PK_TABELA_DE_VENDEDORES] PRIMARY KEY CLUSTERED 
([MATRICULA]));

 -- item 3
INSERT INTO [TABELA DE VENDEDORES]
([NOME], 
[MATRICULA],
[PERCENTUAL COMISSÃO])
VALUES
('Alberto de Sá Verneck','00239',0.08);

 -- item 4
SELECT * FROM [TABELA DE VENDEDORES];